baseURL = 'https://xingyahao.com/'
languageCode = 'en-us'
title = 'Xing Yahao'

theme="archie"
copyright = "© Xing Yahao"
# Code Highlight
pygmentsstyle = "gruvbox"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# documentation https://themes.gohugo.io/themes/archie/

paginate=10

[params]
	mode="toggle"
	favicon = "https://xingyahao.com/favicon.ico"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/keidarcy"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/xingyahao"

[services]
  [services.googleAnalytics]
    id = 'G-FGTFKPMCX2'